blueprints/stock.py
from flask import Blueprint, render_template
import requests

stock = Blueprint('stock', __name__, url_prefix='/stock')
API_URL = 'https://financialmodelingprep.com/api/v3/stock/real-time-price/{ticker}'


def fetch_price(ticker):
    data = requests.get(API_URL.format(ticker=ticker.upper()),
                        params={'apikey': 'demo'}).json()
    return data["price"]


def fetch_income(ticker):
    url = 'https://financialmodelingprep.com/api/v3/financials/income-statement/{}'.format(ticker)
    financials = requests.get(url, params={'period': 'quarter', 'apikey': 'demo'}).json()["financials"]
    financials.sort(key=lambda quarter: quarter["date"])
    return financials


@stock.route('/<ticker>')
def quote(ticker):
    price = fetch_price(ticker)
    return render_template('stock/quote.html', ticker=ticker, stock_price=price)


@stock.route('/<string:ticker>/financials')
def financials(ticker):
    data = fetch_income(ticker)
    return render_template('stock/financials.html', ticker=ticker, financials=data)

templates/base_layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}View Stock Prices{% endblock %} - Stock App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-light bg-light justify-content-between">
            <a href="{{ url_for('home_page') }}" class="navbar-brand">Stock App</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.url_rule.endpoint == 'home_page' %} active {% endif %}">
                    <a class="nav-link" href="{{ url_for('home_page') }}">Home</a>
                </li>
            </ul>
        </nav>
        <div class="container mt-3">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

templates/index.html
{% extends "base_layout.html" %}
{% block title %} Home Page {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm">
        <h1>Welcome to StockApp</h1>
        <div> This is a quick way to view the price of stocks</div>
    </div>
    <div class="col">
        <ul>
            <li> <a href="{{ url_for('stock.quote', ticker='AAPL') }}">View AAPL</a></li>
            <li> <a href="{{ url_for('stock.quote', ticker='GOOGL') }}">View GOOGL</a></li>
            <li> <a href="{{ url_for('stock.quote', ticker='FB') }}">View FB</a></li>
        </ul>
    </div>
</div>

{% endblock %}

templates/macros.html
{% macro stock_quote_link(stock_ticker) %}
<a href="{{ url_for('stock.quote', ticker=ticker) }}">{{ stock_ticker }}</a>
{% endmacro %}

templates/portfolio.html
{% from "macros.html" import stock_quote_link %}
<h2> Your Portfolio: </h2>
<ul>
    {% for ticker in ['AAPL', 'GOOGL', 'FB', 'TSLA'] %}
        <li> {{ stock_quote_link(ticker) }} </li>

    {% endfor %}

</ul>

templates/stock/financials.html
{% extends "base_layout.html" %}
{% block title %} Financials {% endblock %}

{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">As OF</th>
                <th scope="col">Revenue</th>
                <th scope="col">Gross Margin</th>
                <th scope="col">EPS</th>
            </tr>
        </thead>
        <tbody>
            {% for quarter in financials %}
            <tr>
                <th scope="row">{{ quarter["date"] }}</th>
                <td>{{ quarter["Revenue"] }}</td>
                <td>{{ quarter["Gross Margin"] }}</td>
                <td>{{ quarter["EPS"] }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/stock/quote.html
{% extends "base_layout.html" %}
{% block title %} {{ticker}} Stock Quote {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm">
        <h1 class="mb-3">{{ ticker | upper }}</h1>
        <hr />
        <h2> Price: ${{ stock_price | round(2, 'floor') }} </h2>
        <h2> Company Name: {{ company_name | default('Unknown') }} </h2>
    </div>
    <div class="col">
        {% include 'portfolio.html' %}
    </div>
</div>
{% endblock %}